### ISSUE TITLE
Open hand damage on first hit (and on successive hits with unswitching active (duh))

### ISSUE THREAD

**Issue by KalaMiDeviL** [thebombzen/AutoSwitch#11]
It appears that the damage calculation is done before your switch execution.

EDIT: versions:
Minecraft 1.12.2
Forge 14.32.1.2555
Autoswitch 5.6.2

**Comment by Traneptora** [comment]
This is [Minecraft Bug 28289](https://bugs.mojang.com/browse/MC-28289). It's been in the game since around 2013.
