### ISSUE TITLE
Mod uninstalled, but still auto-switch items

### ISSUE THREAD

**Issue by ShiyuLi1997** [thebombzen/AutoSwitch#14]
**Problem:** simple. I installed the latest version through 9minecraft.com.(I found it there). Then, whenever it switch weapons, the graphic somehow jumps the frame. It means when I hit the dirt block with an axe, it switch to shovel and start digging and this particular moment, the frame stucked for a milisecond. 

**Problem2:**So I uninstall the mod. but it still functioning.(no idea how.) I uninstall and reinstall minecraft doesn't solve the problem. Sometimes, it switch to a wrong tool.(guess its a bug.) But why is it still working after I delete everything in the ".minecraft" file under "%appdata%"? 

**Discussion:** Does it store data somewhere else? Does it change the Minecraft jar sooooo deep that a re-install dont eleminate the function?

**WhatIamDoing** I am spending time picking the mod I wanna play with, and try to doing a streaming and a server. And the water is too deep. Plz help.

Li.

**Comment by Traneptora** [comment]
Install it through the proper install instructions. I'm not responsible for someone else's broken installer.

**Comment by MrRobotVPN** [comment]
@ShiyuLi1997 
**If you have multiple account on the computer make sure you are on the right User account on your PC**
Open windows explorer click View -> Options -> Change -> View -> Hidden Files and folders
Show hidden files and folders
just in case you marked the mod or profile as hidden

Depending on what launcher you use 
Delete any AutoSwitch profiles in
%userProfile%\Documents\Curse\Minecraft\Install\versions
%appdata%\.technic\modpacks\vanilla\bin\version
C:\ftb\versions or %appdata%\ftb\versions

Or any Autoswitch mods in
%appdata%\.minecraft\mods\
%appdata%\.minecraft\mods\1.12.2
%appdata%\.atlauncher\Instances\ModPackExample\mods
%appdata%\.technic\modpacks\vanilla\mods
C:\ftb\ExampleModPack\minecraft\mods or %appdata%\ftb\ExampleModPack\minecraft\mods

Are you running forge or Liteloader at all? try running vanilla and let me know if this issue keeps happening.
