### ISSUE TITLE
1.12 Update

### ISSUE THREAD

**Issue by EpiXSim0n** [thebombzen/AutoSwitch#4]
Is there an Update coming for 1.12 or is this repository inactive ?

**Comment by thebombzen** [comment]
Perhaps at some point

**Comment by thebombzen** [comment]
I'm very busy right now and dealing with lots of things, and I don't quite have the time or the energy to maintain the codebase. I haven't abandoned the project, It's just sort of on hold while I deal with IRL priorities.
